### ISSUE TITLE
Theme seems to be broken with Grav 1.7.9

### ISSUE THREAD

**Issue by right105** [danzinger/grav-theme-vela#12]
Hi, 
unfortunately your theme does not work on a fresh Grave 1.7.9 installation.

Please see attachement for details.

Can you check this?

Thanks

Stefan

![HTML source](https://user-images.githubusercontent.com/81696828/113161851-0d612f80-923f-11eb-8bdb-62bb35417d39.png)
![Screenshot Grave Startpage](https://user-images.githubusercontent.com/81696828/113161857-0e925c80-923f-11eb-9477-e6bc02673612.png)

**Comment by danzinger** [comment]
Thank you! I already know about this problem. This is because twig-auto-escaping is now enabled by default. See here for a fix: https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#twig

This can be fixed in `user/config/system.yaml` or via two settings in the GRAV Backend. (Auto Escape Variables to NO and Twig Compatibility Mode to YES).

However, I will work on this problem asap so that no additional settings are needed after a fresh installation.

**Comment by right105** [comment]
Thanks a lot!
Setting these two parameters solved the problem!

Thanks for this nice theme and your great support!

**Comment by danzinger** [comment]
This was now fixed with the v1.2.3 release. No additional settings should be needed anymore on a fresh install. Thanks again for bringing up this issue!
