### ISSUE TITLE
Actions of menu

### ISSUE THREAD

**Issue by Maclaon** [danzinger/grav-theme-vela#2]
The action of showing page content of **directory** when click dropdown menu would be better?

**Comment by danzinger** [comment]
I dont know if I understand correctly. I would be happy to see a pull request. Or, can you explain your request in more detail and provide a sample page structure where you explain what should happen?

Consider the learn2 theme on small screens: https://learn.getgrav.org If you select a toplevel menu entry (Content, Themes, Plugins), then the "titlepage" is loaded and the menu is closed. If you then want to navigate to a child (e.g. Content --> Media) you have to re-open the menu. This might be fine for the purpose of a documentation, but not to structure large amounts of nested content.

IMHO the idea of a dropdown menu is that any container that holds children is itself not routable. Everything else would result in weired user experience.

**Comment by Maclaon** [comment]
oh, thanks! let me give u some sample page that i want to do! Take [https://learn.getgrav.org](https://learn.getgrav.org/15) for example. when i click the left-side dropdown menu, such as [Content](https://learn.getgrav.org/15/content), then the main content can give me some content. but in your theme, when i click left-side dropdown menu, such as [Home](http://mathcode.cn/), the main content shows the last content. 

![image](https://user-images.githubusercontent.com/5398475/55707134-7a0d0f00-5a15-11e9-931c-5750334ef8b9.png)

![image](https://user-images.githubusercontent.com/5398475/55707516-5a2a1b00-5a16-11e9-9a0d-68d3fcd58bcc.png)

**Comment by danzinger** [comment]
Yes, you are right! In the Vela theme, all pages where you directly want to see content should not have sub-pages. Your "Home" has a subpage "machine learning" and is therefore only a "container" for "machine learning" and not a "real" page. It is intended behavoir that the content of "Home" cannot be reached via the menu. 

The Learn2 theme is quite unusual in this matter. Try it on a small screen (mobile phone), where the menu is closed by default. If you open the menu and click "Content", the titlepage of "Content" (as in your picture) shows up but the menu closes. If I want to go to a subpage like “Content/Media”, then I need to re-open the menu. I find this very uncomfortable. I want to see directly what are the subpages of “Content”, without opening the menu again.

In Learn2 on a big screen you don’t realize this problem, because the menu is open by default. You can easily navigate to your content without re-opening the menu again.

**Comment by Maclaon** [comment]
Thanks! I am not good at php.  Does [metismenu](https://github.com/onokumus/metismenu) support that feature or does any other way to solve that issue? This theme is awesome, simple, clear.

**Comment by danzinger** [comment]
Thank you! Glad that you like this theme. 
No, unfortunately this is not possible. I would simply recommend a slightly different page structure, like the following example. All pages with X you can reach from the menu. Content you like to write in `topic` you may just write in `introduction`. 

```
home X (start-page)
topic
   introduction X
   subpage X
   subpage X
topic  
   introduction X
   subpage
      subpage introduction X
      subsubpage X
      subsubpage X
topic  X
...
```

**Comment by Maclaon** [comment]
OK, Thanks, I will try it! This is more clear!

**Comment by danzinger** [comment]
Hello! I recently implemented the requested feature. If you install the theme update, you will find some new options in the theme configuration. Just enable "Parent pages routable in menu". Additionally I implemented a feature that the menu does not close on large screens if you navigate to a page ("Desktop Mode"). I recommend enabling this option as well. Ask if you have any questions. 
You can also go back to version 1.0.1 any time, if you run into problems with the update. 

Cheers, Matthias
